Vagrant.configure(2) do |config|
  config.vm.box = "fedora/36-cloud-base"

  config.vm.define :vagrant_tekton do |vagrant_host|
    vagrant_host.vm.hostname = "tekton"
    vagrant_host.vm.provider :libvirt do |domain|
      domain.cpus = 2
      domain.memory = 16384
      domain.nested = true
    end

    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.synced_folder ".", "/home/vagrant", disabled: true

    vagrant_host.vm.provision "shell", privileged: true, inline: "dnf install -y podman make git"
    vagrant_host.vm.provision "shell", privileged: true, inline: "systemctl enable --now podman.socket"

    vagrant_host.vm.provision "shell", privileged: true, path: "config.sh"

  end

end
